package com.prueba.tecnica.parqueaderos.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Date;
@Data
@NoArgsConstructor
@Builder
@AllArgsConstructor
@DynamoDBTable(tableName = "Movements")
public class Movements {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "MovementId")
    private String movementId;
    @DynamoDBAttribute(attributeName = "VehicleType")
    private String vehicleType;
    @DynamoDBAttribute(attributeName = "Plate")
    private String plate;
    @DynamoDBAttribute(attributeName = "EntryDate")
    private Date entryDate;
    @DynamoDBAttribute(attributeName = "ExitDate")
    private Date exitDate;
    @DynamoDBAttribute(attributeName = "ServiceTime")
    private String serviceTime;
    @DynamoDBAttribute(attributeName = "State")
    private Integer state;

    public Movements(String vehicleType, String plate, Date entryDate, Integer state) {
        this.vehicleType = vehicleType;
        this.plate = plate;
        this.entryDate = entryDate;
        this.state = state;
    }
}
